const file=document.querySelector('#file'),drop=document.querySelector('#drop'),video=document.querySelector('#video'),thumb=document.querySelector('#thumb'),placeholder=document.querySelector('#placeholder'),meta=document.querySelector('#meta'),empty=document.querySelector('#empty'),processBtn=document.querySelector('#process'),status=document.querySelector('#status');
const sliders=['strength','harsh','smooth','warm','level'];
sliders.forEach(id=>{const el=document.querySelector('#'+id),out=document.querySelector('#'+id+'Out');el.addEventListener('input',()=>out.textContent=id==='level'?el.value+' dB':el.value)});
const presets={light:[30,35,25,20,0],natural:[60,70,50,40,0],strong:[85,90,75,60,-1]};
document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-preset]').forEach(x=>x.classList.remove('primary'));b.classList.add('primary');presets[b.dataset.preset].forEach((v,i)=>{const el=document.querySelector('#'+sliders[i]);el.value=v;el.dispatchEvent(new Event('input'))})}));
function load(f){if(!f||!f.type.startsWith('video/'))return;const url=URL.createObjectURL(f);video.src=url;thumb.src=url;thumb.style.display='block';placeholder.style.display='none';empty.style.display='none';processBtn.disabled=false;video.onloadedmetadata=()=>{const dur=Math.round(video.duration);meta.innerHTML='<b>'+f.name+'</b><br>'+Math.round(f.size/1048576)+' MB<br>'+dur+' sec';};status.textContent='Clip loaded. V0.1 processing engine is the next build step.'}
file.addEventListener('change',()=>load(file.files[0]));drop.addEventListener('dragover',e=>{e.preventDefault();drop.style.borderColor='#159eff'});drop.addEventListener('dragleave',()=>drop.style.borderColor='');drop.addEventListener('drop',e=>{e.preventDefault();drop.style.borderColor='';load(e.dataTransfer.files[0])});
processBtn.addEventListener('click',()=>status.textContent='UI test only: audio processing is not connected yet.');
document.querySelector('#original').addEventListener('click',()=>status.textContent='Original A/B mode selected.');
document.querySelector('#processed').addEventListener('click',()=>status.textContent='Processed A/B mode selected — engine not connected yet.');